# build stage
FROM {{ nodeImage }} as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM {{ nginxImage }} as production
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./dockerizer/default.conf /etc/nginx/conf.d/default.conf
EXPOSE {{ port }}
CMD ["nginx", "-g", "daemon off;"]