# build stage
FROM {{ node_image }} as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM {{ nginx_image }} as production
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE {{ port }}
CMD ["nginx", "-g", "daemon off;"]