# Creating multi-stage build for production
FROM node:{{nodeVersion}}-alpine AS build
RUN apk update && apk add --no-cache {{buildStagePackages}} > /dev/null 2>&1
ENV NODE_ENV=production

WORKDIR /opt/
COPY package.json yarn.lock ./
RUN yarn global add node-gyp

RUN yarn config set network-timeout 600000 -g && yarn install --{{nodeEnv}}
ENV PATH /opt/node_modules/.bin:$PATH
WORKDIR /opt/app
COPY . .
RUN yarn build

# Creating final production image
FROM node:{{nodeVersion}}-alpine
RUN apk add --no-cache {{productionStagePackages}}
ENV NODE_ENV=production
WORKDIR /opt/
COPY --from=build /opt/node_modules ./node_modules
WORKDIR /opt/app
COPY --from=build /opt/app ./
ENV PATH /opt/node_modules/.bin:$PATH

RUN chown -R {{user}}:{{user}} /opt/app
USER {{user}}
EXPOSE {{port}}
CMD ["yarn", "start"]