# build stage
FROM {{ nodeImage }} as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM {{ nginxImage }} as production
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE {{ port }}
CMD ["nginx", "-g", "daemon off;"]