FROM {{ phpImage }}

COPY ./dockerizer/php.ini /opt/docker/etc/php/php.ini

{% if webServer === "apache" -%}
COPY ./dockerizer/vhost.conf /opt/docker/etc/httpd/vhost.conf
{% else -%}
COPY ./dockerizer/vhost.conf /opt/docker/etc/nginx/vhost.conf
{%- endif %}

{% if phpUnixSocket -%}
ENV WEB_PHP_SOCKET {{ phpUnixSocketValue }}
{% endif -%}

{% if runComposerInstall %}
COPY composer.json composer.lock /app/
RUN composer install --no-interaction --no-scripts --no-suggest
{% endif %}

COPY . /app

# Set the correct permissions
# RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
